using System.Text.Json.Serialization;
using Aiko.Application.Agents;
using Aiko.Application.Contracts;
using Aiko.Application.Prioritization;
using Aiko.Domain.Cards;
using Aiko.Domain.Execution;
using Aiko.Domain.Workflow;

namespace Aiko.Server.Contracts;

/// <summary>
/// Source-generated JSON context of the daemon HTTP API (camelCase, string enum values).
/// </summary>
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(ShutdownResponse))]
[JsonSerializable(typeof(SystemResponse))]
[JsonSerializable(typeof(RegisteredProject))]
[JsonSerializable(typeof(RegisteredProject[]))]
[JsonSerializable(typeof(IReadOnlyList<RegisteredProject>))]
[JsonSerializable(typeof(InitializeProjectRequest))]
[JsonSerializable(typeof(ProjectTemplateSummary))]
[JsonSerializable(typeof(IReadOnlyList<ProjectTemplateSummary>))]
[JsonSerializable(typeof(CreateTemplateRequest))]
[JsonSerializable(typeof(CreateTemplateFromProjectRequest))]
[JsonSerializable(typeof(UpdateTemplateRequest))]
[JsonSerializable(typeof(ExportTemplateRequest))]
[JsonSerializable(typeof(ImportTemplateRequest))]
[JsonSerializable(typeof(ApplyTemplateRequest))]
[JsonSerializable(typeof(ProjectTemplate))]
[JsonSerializable(typeof(TemplateDocument))]
[JsonSerializable(typeof(ReindexResult))]
[JsonSerializable(typeof(Card))]
[JsonSerializable(typeof(CardBlockerView))]
[JsonSerializable(typeof(IReadOnlyList<CardBlockerView>))]
[JsonSerializable(typeof(IReadOnlyList<Card>))]
[JsonSerializable(typeof(CardRelation))]
[JsonSerializable(typeof(IReadOnlyList<CardRelation>))]
[JsonSerializable(typeof(WorkflowDefinition))]
[JsonSerializable(typeof(IReadOnlyList<WorkflowDefinition>))]
[JsonSerializable(typeof(BoardProjectionDefinition))]
[JsonSerializable(typeof(IReadOnlyList<BoardProjectionDefinition>))]
[JsonSerializable(typeof(ProjectBoardSnapshot))]
[JsonSerializable(typeof(CardPriority))]
[JsonSerializable(typeof(IReadOnlyList<CardPriority>))]
[JsonSerializable(typeof(AppSettings))]
[JsonSerializable(typeof(AppSettingsView))]
[JsonSerializable(typeof(AikoEvent))]
[JsonSerializable(typeof(IReadOnlyList<AikoEvent>))]
[JsonSerializable(typeof(MoveCardRequest))]
[JsonSerializable(typeof(UpdateWorkflowRequest))]
[JsonSerializable(typeof(CreateWorkflowRequest))]
[JsonSerializable(typeof(RenameWorkflowRequest))]
[JsonSerializable(typeof(UpdateCardRequest))]
[JsonSerializable(typeof(CreateCardRequest))]
[JsonSerializable(typeof(EstimateCardRequest))]
[JsonSerializable(typeof(PairRequest))]
[JsonSerializable(typeof(PairResponse))]
[JsonSerializable(typeof(UpdateArtifactRequest))]
[JsonSerializable(typeof(GitStatus))]
[JsonSerializable(typeof(GitCommit))]
[JsonSerializable(typeof(IReadOnlyList<GitCommit>))]
[JsonSerializable(typeof(GitOverview))]
[JsonSerializable(typeof(GitFileDiff))]
[JsonSerializable(typeof(IReadOnlyList<GitFileDiff>))]
[JsonSerializable(typeof(GitCardDiff))]
[JsonSerializable(typeof(DaemonTelemetry))]
[JsonSerializable(typeof(ProjectAnalytics))]
[JsonSerializable(typeof(AnalyticsBucket))]
[JsonSerializable(typeof(IReadOnlyList<AnalyticsBucket>))]
[JsonSerializable(typeof(CardComment))]
[JsonSerializable(typeof(IReadOnlyList<CardComment>))]
[JsonSerializable(typeof(AddCommentRequest))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(RevisionConflictResponse))]
[JsonSerializable(typeof(ArtifactConflictResponse))]
[JsonSerializable(typeof(CardArtifactSummary))]
[JsonSerializable(typeof(IReadOnlyList<CardArtifactSummary>))]
[JsonSerializable(typeof(CardArtifactDocument))]
[JsonSerializable(typeof(IReadOnlyList<MemoryDocument>))]
[JsonSerializable(typeof(ActivityDay))]
[JsonSerializable(typeof(IReadOnlyList<ActivityDay>))]
[JsonSerializable(typeof(WorkshopDiagnostics))]
[JsonSerializable(typeof(DiagnosticFinding))]
[JsonSerializable(typeof(IReadOnlyList<DiagnosticFinding>))]
[JsonSerializable(typeof(DirectoryListing))]
[JsonSerializable(typeof(StageExecution))]
[JsonSerializable(typeof(IReadOnlyList<StageExecution>))]
[JsonSerializable(typeof(AgentAdapterOption))]
[JsonSerializable(typeof(IReadOnlyList<AgentAdapterOption>))]
[JsonSerializable(typeof(AgentUserScope))]
[JsonSerializable(typeof(AgentProjectConnection))]
[JsonSerializable(typeof(IReadOnlyList<AgentProjectConnection>))]
[JsonSerializable(typeof(AgentConnectionResponse))]
[JsonSerializable(typeof(PlanAgentInstallationRequest))]
[JsonSerializable(typeof(UnifiedInstallationPlan))]
[JsonSerializable(typeof(InstallationFileResult))]
[JsonSerializable(typeof(AgentInstallationResult))]
[JsonSerializable(typeof(UnifiedInstallationResult))]
[JsonSerializable(typeof(UnifiedUninstallationPlan))]
[JsonSerializable(typeof(UnifiedUninstallationResult))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    UseStringEnumConverter = true)]
internal sealed partial class ServerJsonContext : JsonSerializerContext;
